### ISSUE TITLE
Sorry, this has no relation with the repository.

### ISSUE THREAD

**Issue by DarkMrMelther** [MishaIac/YurisKeyFinder#1]
Sorry for using this repository to contact you, but since a few days ago I'm looking for a way to modify some parameters of ToToNo, but I can't find a way to re-compile the code after passing it through the NutCracker. So as I saw that you got it I came to ask you, if you could help me I would appreciate it.
Thanks and sorry in advance.

**Comment by MishaIac** [comment]
Unfortunately, I don't know how to compile the .nut files. If you use official tools, the .nut files will most likely crash the game, or the tool will not be able to compile the file at all.

You could try leaving it as is, without compiling, but there's no guarantee that it will work well.

You can also try the method that marcussacana (creator of MwareStuff) told me: https://github.com/marcussacana/MwareStuff/issues/7#issuecomment-660823501
This method worked for me. Of course, this method only works if the .nut files can be compiled.

**Comment by DarkMrMelther** [comment]
That method I was trying to use, but I am unable to recompile the script. What do I have to do?

**Comment by MishaIac** [comment]
Then I'm sorry, but I can't help you. I had some .nut files from Tokyo Necro able to recompile, but not all files.
By the way, which parameters do you want to change in Totono? Perhaps they could be changed in some other way.

**Comment by DarkMrMelther** [comment]
I need to change some position parameters in the settings ui, also, if you can describe me the method by which you recompiled the files you were able to I would appreciate it.

**Comment by MishaIac** [comment]
Can you give me one decompiled file? I'll try to recompile it.

**Comment by DarkMrMelther** [comment]
[sys_config.nut.txt](https://github.com/MishaIac/YurisKeyFinder/files/7697669/sys_config.nut.txt)
Here you have, I hope you can

**Comment by MishaIac** [comment]
Unfortunately, I couldn't. After all, not all files can be recompiled.

**Comment by DarkMrMelther** [comment]
Mmmm... What steps do you do? Maybe I can think something

**Comment by MishaIac** [comment]
It will not work, because in the file, some lines have broken syntax. Most likely, it is NutCracker's fault, and it broke the syntax, or it should be, because the engine accepts this syntax. It seems to me that this is the second option. In this case, you can not compile with available tools, so, you have to write your own compiler, which is of course very difficult, and is unlikely someone will do this. And some other files from the game, can compile only because they do not have this broken syntax.

**Comment by DarkMrMelther** [comment]
I understand, well, I would like to try with other files but what should I do to recompile them?

**Comment by MishaIac** [comment]
Try this: https://github.com/vancityspiller/.nut-Compile-Tool

**Comment by DarkMrMelther** [comment]
Thank you very much, I close the issue for the moment, if I find a way to do it I will inform you.

**Comment by MishaIac** [comment]
[sys_config.nut.txt](https://github.com/MishaIac/YurisKeyFinder/files/7697723/sys_config.nut.txt) - compiled
[sys_config.nut.txt](https://github.com/MishaIac/YurisKeyFinder/files/7697726/sys_config.nut.txt) - code without broken syntax
Still, I was able to compile the file, removing the broken syntax, however, I do not think it will work in the game.

**Comment by MishaIac** [comment]
@DarkMrMewtho In any case, you can change that file without the broken syntax, and compile through the .nut-Compile-Tool I sent above. Maybe it will work,
